Repository openshift/osde2e-common, pull requests merged in 2023-06, with the labels that each got.

#2 Initialize directory structure with clients package
  .gitignore
  Makefile
  README.md
  go.mod
  go.sum
  pkg/clients/ocm/client.go
  pkg/clients/openshift/client.go
  pkg/clients/prometheus/client.go
Labels: approved, lgtm

#3 custom test utils
  go.mod
  go.sum
  pkg/gomega/assertions/eventually_deployment.go
  pkg/gomega/matchers/contain_item_with_prefix.go
  pkg/gomega/matchers/contain_item_with_prefix_test.go
  pkg/gomega/matchers/deployment_available.go
  pkg/gomega/matchers/deployment_available_test.go
  pkg/gomega/matchers/matchers_tests_suite_test.go
Labels: approved, lgtm

#6 Initialize projects readme
  README.md
Labels: approved, lgtm

#7 assertion for Config map exists
  pkg/gomega/assertions/eventually_configmap.go
Labels: approved, lgtm

#10 Modify gomega configmap assertion docstring
  pkg/gomega/assertions/eventually_configmap.go
Labels: approved, lgtm, tide/merge-method-squash

#4 Support ROSA Cluster Create/Delete
  examples/rosacreatecluster/rosacreatecluster.go
  examples/rosadeletecluster/rosadeletecluster.go
  go.mod
  go.sum
  internal/cmd/cmd.go
  internal/terraform/terraform.go
  pkg/clients/ocm/credentials.go
  pkg/clients/openshift/client.go
  pkg/clients/openshift/healthcheck.go
  pkg/clouds/aws/credentials.go
  pkg/openshift/rosa/accountroles.go
  pkg/openshift/rosa/assets.go
  pkg/openshift/rosa/assets/setup-hcp-vpc.tf
  pkg/openshift/rosa/cluster.go
  pkg/openshift/rosa/gologrkeys.go
  pkg/openshift/rosa/hcpvpc.go
  pkg/openshift/rosa/logs.go
  pkg/openshift/rosa/oidcconfig.go
  pkg/openshift/rosa/operatorroles.go
  pkg/openshift/rosa/rosa.go
Labels: approved, lgtm

#12 SDCICD-1043: Port missing ROSA create cluster options from osde2e
  pkg/openshift/rosa/cluster.go
Labels: approved, lgtm, jira/valid-reference

#14 ROSA provider: perform a region check prior to cluster creation
  pkg/openshift/rosa/cluster.go
  pkg/openshift/rosa/regions.go
Labels: approved, lgtm

#15 ROSA provider: support getting versions
  pkg/openshift/rosa/cluster.go
  pkg/openshift/rosa/versions.go
Labels: approved, lgtm

#16 ROSA provider: add support for randomly selecting AWS region to use
  pkg/clouds/aws/credentials.go
  pkg/openshift/rosa/regions.go
  pkg/openshift/rosa/rosa.go
Labels: approved, lgtm

#17 ROSA provider: add a field to turn on/off vpc deletion
  pkg/openshift/rosa/cluster.go
Labels: approved, lgtm

#18 ROSA provider: update HCP cluster health check to verify compute node count
  pkg/clients/openshift/healthcheck.go
  pkg/openshift/rosa/cluster.go
Labels: approved, lgtm

#19 ROSA provider: add option to skip health checks
  pkg/openshift/rosa/cluster.go
Labels: approved, lgtm

#20 ROSA provider: modify regions custom error to support different actions
  pkg/openshift/rosa/regions.go
Labels: approved, lgtm

#21 ROSA provider: pass in cluster name to waitForClusterToBeHealthy over cluster ID
  pkg/openshift/rosa/cluster.go
Labels: approved, lgtm

#22 ROSA provider: adjust clean up operations based on cluster settings
  pkg/openshift/rosa/cluster.go
  pkg/openshift/rosa/oidcconfig.go
  pkg/openshift/rosa/operatorroles.go
Labels: approved, lgtm

#23 ROSA provider: add a field to turn on/off oidc config create/delete
  pkg/openshift/rosa/cluster.go
Labels: approved, lgtm

#24 SDCICD-1049: ROSA Provider Updates
  examples/rosadeletecluster/rosadeletecluster.go
  pkg/clients/ocm/credentials.go
  pkg/openshift/rosa/cluster.go
  pkg/openshift/rosa/rosa.go
Labels: approved, lgtm, jira/valid-reference
